---
title: "Necromass Database: Exploration"
output: 
  github_document:
  html_preview: true
---


---

```{r setup, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      warning = FALSE)
```

```{r}
source("2-code/0-packages.R")
targets::tar_load(db_processed)

db_processed = read.csv("3-database/database_data.csv", na = "")

```

## FIGURES 

### Geographical Distribution

```{r map_all_climate}

# mapping all MAT-MAP data points ----
KoeppenGeigerASCII = readxl::read_xlsx("1-data/geographic_databases/KoeppenGeigerASCII.xlsx")
# KG climate zone map of all the globe
map_climate_regions_all = 
  KoeppenGeigerASCII %>% 
  mutate(ClimateTypes = case_when(grepl("A", ClimateTypes) ~ "equatorial",
                                  grepl("B", ClimateTypes) ~ "arid",
                                  grepl("C", ClimateTypes) ~ "temperate",
                                  grepl("D", ClimateTypes) ~ "snow",
                                  grepl("E", ClimateTypes) ~ "polar")) %>% 
  #  reorder_biome_levels() %>% 
  ggplot(aes(x = Longitude, y = Latitude, color = ClimateTypes))+
  geom_point()+
  scale_color_viridis_d(option = "turbo", direction = -1, na.translate = F)+
  labs(color = "",
       x = "",
       y = "")+
  theme_kp()+
  theme(axis.text = element_blank(),
        panel.grid = element_blank(),
        axis.ticks = element_blank())+
  NULL

```


```{r map_data_points}
library(rnaturalearth)
library(rnaturalearthdata)
library(sf)

# mapping our data distribution ----
world <- ne_countries(scale = "medium",  returnclass = "sf", type = "countries")

sndb_map_data = 
  db_processed %>% 
  distinct(Latitude, Longitude, ClimateTypes) %>% 
  drop_na() %>% 
  mutate(ClimateTypes = factor(ClimateTypes, levels = c("arid", "equatorial", "temperate", "snow", "polar")))

world %>% 
  ggplot()+
  geom_sf(color = NA, alpha = 0.7)+
  geom_point(data = sndb_map_data,
             aes(x = Longitude, y = Latitude,
                 color = ClimateTypes), 
             size = 2)+
  labs(color = "",
       x = "",
       y = "")+
  scale_color_viridis_d(option = "turbo", direction = -1, na.translate = F)+
  #theme_void()+
  theme_kp()+
  theme(axis.text = element_text(color = "black"),
        legend.position = "top")+
  guides(colour = guide_legend(nrow = 1))+
  NULL

```


### Distribution by MAT-MAP

```{r mat-map, fig.height=5.5, fig.width=6.5}

# plot MAT/MAP distribution
  db_processed %>% 
    ggplot(aes(x = MAT, y = MAP/10))+
    geom_point(aes(color = ClimateTypes), size = 3)+
    labs(x = "
         Mean annual temperature (°C)",
         y = "Mean annual precipitation (cm)
         ")+
    scale_color_viridis_d(option = "turbo", direction = -1, na.translate = F)+
    theme_kp()+
    theme(legend.position = c(0.15, 0.8))+
    NULL
```

### Distribution by Whittaker Biome

```{r whittaker, fig.height=5, fig.width=8}

# devtools::install_github("valentinitnelav/plotbiomes", force = TRUE)
  # library(plotbiomes)
  
  ggplot() +
    # add biome polygons
    geom_polygon(data = Whittaker_biomes,
                 aes(x    = temp_c,
                     y    = precp_cm,
                     fill = biome),
                 # adjust polygon borders
                 colour = "gray98",
                 linewidth = 1) +
    geom_point(data = db_processed %>% mutate(mat = as.numeric(MAT), map_mm = as.numeric(MAP)), 
               aes(x = mat, y = map_mm/10), 
               size = 2,
               show.legend = F)+
    labs(x = "
         Mean annual temperature (°C)",
         y = "Mean annual precipitation (cm)
         ")+
    theme_kp()+
    theme(legend.position = "right")

```


### Distribution by ecosystem

```{r subset}
db_subset <- 
  db_processed %>% 
  dplyr::select(contains("necromass"), ecosystem, ClimateTypes, biome_name, clay, fraction_scheme, horizon) %>% 
  filter(fraction_scheme == "bulk soil") %>% 
  mutate(bacterial_percent = 100 * bacterial_necromass_C/microbial_necromass_C)
```


```{r ecosystem_stats}
# stats

a_mnc = aov(microbial_necromass_C ~ ecosystem, data = db_subset %>% filter(!is.na(ecosystem)))
h_mnc = agricolae::HSD.test(a_mnc, "ecosystem")$groups %>% rownames_to_column("ecosystem")

a_bnc = aov((bacterial_percent) ~ ecosystem, data = db_subset %>% filter(!is.na(ecosystem)))
h_bnc = agricolae::HSD.test(a_bnc, "ecosystem")$groups %>% rownames_to_column("ecosystem")

```

```{r jitter-ecosystem, fig.height=4, fig.width=7}

gg_mnc = 
  db_subset %>% 
  filter(!is.na(ecosystem)) %>% 
  ggplot(aes(x = ecosystem, y = microbial_necromass_C/1000,
             color = ecosystem, fill = ecosystem))+
  ggdist::stat_halfeye(aes(), 
                       size = 1, alpha = 0.5,
                       position = position_nudge(x = 0.2), width = 0.5, 
                       #slab_color = "black"
  )+
  geom_jitter(aes(), width = 0.1, )  +
  geom_text(data = h_mnc,
            aes(y = 200, label = groups), color = "black", size = 5)+
  labs(y = "Microbial Necromass C, g/kg",
       x = "Ecosystem")+
  scale_y_continuous(labels = scales::comma)+
  scale_color_brewer(palette = "Dark2", direction = -1)+
  scale_fill_brewer(palette = "Dark2", direction = -1)+
  theme_kp()+
  theme(legend.position = "none")


gg_bnc = 
  db_subset %>% 
  filter(!is.na(ecosystem)) %>% 
  ggplot(aes(x = ecosystem, y = bacterial_percent,
             color = ecosystem, fill = ecosystem))+
  ggdist::stat_halfeye(aes(), 
                       size = 1, alpha = 0.5,
                       position = position_nudge(x = 0.2), width = 0.5, 
                       #slab_color = "black"
  )+
  geom_jitter(aes(), width = 0.1, )  +
    geom_text(data = h_bnc, 
            aes(y = 110, label = groups), color = "black", size = 5)+
labs(y = "BNC:MNC, %",
       x = "Ecosystem")+
  scale_y_continuous(labels = scales::comma)+
  scale_color_brewer(palette = "Dark2", direction = -1)+
  scale_fill_brewer(palette = "Dark2", direction = -1)+
  theme_kp()+
  theme(legend.position = "none")

```



```{r}
gg_depth <- 
  db_processed %>% 
  filter(lyrtop_cm <= 100) %>% 
  ggplot(aes(y = lyrbot_cm, x = microbial_necromass_C/1000))+
  geom_point(color = "darkgreen")+
  labs(x = "Microbial Necromass C, g/kg",
       y = "Bottom depth, cm")+
  scale_y_reverse()

gg_lat = 
  db_processed %>% 
  filter(!is.na(ecosystem)) %>% 
  ggplot(aes(y = Latitude, x = microbial_necromass_C/1000))+
  geom_point(color = "brown")+
  scale_color_brewer(palette = "Dark2", direction = -1)+
  labs(x = "Microbial Necromass C, g/kg")+
  theme_kp()
  
```


```{r}
cowplot::plot_grid(gg_mnc, gg_bnc, gg_lat, gg_depth, labels = "AUTO")
```


#### Sample count by depth
```{r depth}

depth_summary = 
  db_processed %>%
  dplyr::select(lyrtop_cm, lyrbot_cm) %>% 
  mutate_all(as.numeric) %>% 
  filter(lyrtop_cm < 1000) %>% 
  mutate(lyrtop_cm = round(lyrtop_cm, digits = -1),
         lyrbot_cm = round(lyrbot_cm, digits = -1)) %>% 
  group_by(lyrtop_cm, lyrbot_cm) %>% 
  dplyr::summarise(n = n()) %>% 
  ungroup() %>% 
  arrange(n, lyrtop_cm, lyrbot_cm)
  
library(scales)
depth_summary %>% 
  ggplot(aes(x = n))+
  geom_hline(yintercept = 20, color = "grey", linetype = "longdash")+
  geom_segment(aes(y = lyrtop_cm, yend = lyrbot_cm, xend = n,
                   color = interaction(lyrtop_cm, lyrbot_cm)),
               show.legend = F, linewidth = 2)+
  geom_point(aes(y = lyrtop_cm), size = 4)+
  geom_point(aes(y = lyrbot_cm), size = 4)+
  scale_x_continuous(trans = c("log10", "reverse"))+
  scale_y_reverse()+
  labs(x = "count", y = "depth, cm")
```

of the 3000+ datapoints, 2512 data points are in the top 20 cm (lyrbot_cm >= 20)


```{r}

db_processed %>% 
  ggplot(aes(x = as.numeric(lyrbot_cm)))+
  geom_density()+
  geom_histogram()+
  coord_flip()+
  scale_x_reverse()+
  labs(x = "bottom depth, cm")


```


## TABLES

### Sample count by biome

```{r}
db_processed %>% 
  group_by(ClimateTypes) %>% 
  dplyr::summarise(n = n()) %>% 
  knitr::kable()
```


### Sample count by ecosystem
```{r}
db_processed %>% 
  group_by(ecosystem) %>% 
  dplyr::summarise(n = n()) %>% 
  knitr::kable()
```


---

<details>
<summary> Session Info </summary>

Date run: `r Sys.Date()`

```{r}
sessionInfo()
```

</details>